# SPDX-FileCopyrightText: Copyright (c) 2024-2025 Infineon Technologies AG
# SPDX-License-Identifier: MIT

version = 1

[[annotations]] 
path =  ["docs/images/*.png", "docs/images/*.jpg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) 2024-2025 Infineon Technologies AG"
SPDX-License-Identifier = "CC-BY-NC-ND-4.0"

